### ISSUE TITLE
Can not set Lightify Tunable White

### ISSUE THREAD

**Issue by 77Seven777** [rainlake/homebridge-platform-lightify#1]
The plugin actually works supper.
The lamps are displayed and you can use them. The RGBW lamps can also change the color and also the light temperature.
Unfortunately, the turnable white lamps can not adjust the "light-temparatur". Is it possible to add this to the plugin?
thank you

**Comment by rainlake** [comment]
Sorry for this late reply, HomeKit itself does not support "temperature". there is nothing we can do.

**Comment by apexad** [comment]
You should check out https://github.com/lbohlmann/homebridge-lightify-tunablewhite-e14
He did it using color, which HomeKit does support.

**Comment by rainlake** [comment]
I highly doubt it will work. HUE color translate to temperature will result huge range than tunable bulb can support
