### ISSUE TITLE
hang after reboot

### ISSUE THREAD

**Issue by Matthias-Loenartz** [rainlake/homebridge-platform-lightify#12]
Hello,
I use systemd to launch homebridge, but after every reboot the last log message is "Oct 08 14:11:49 raspberrypi homebridge[434]: [2017-10-8 14:11:49] [Lightify] Discovered failed connect timeout".
After a manuell restart it works again, also the autostart works when I remove lightify from config.json.
The start file waits for network is online:

"[Unit]
Description=Node.js HomeKit Server
After=network-online.target syslog.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/homebridge
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target"

Hope you can help,
with best regards Matthias Lönartz

**Comment by rainlake** [comment]
sorry, Can not help you right now. I'm moving, all devices are packed.

**Comment by Matthias-Loenartz** [comment]
Hello,
after a clean install on another raspberry it works well, so sorry for the circumstances.

With best regards Matthias Lönartz
