### ISSUE TITLE
Discover Failed - Timeout 

### ISSUE THREAD

**Issue by balsman225** [rainlake/homebridge-platform-lightify#13]
I am having some issues with with plugin timing out sporadically. 
When this happens I am still able to ping the controller without issue and can control the lights from the Lightify app without issue. Restarting HomeBridge will correct this issue or overtime it will start responding again. 
I have one gateway, 8 PAR38  bulbs and 2 A19 white bulbs.
Please let me know if you need any other info - Thank you for your assistance and support

![lightify timeout](https://user-images.githubusercontent.com/4239330/33744826-ccd4a6b6-db78-11e7-8cea-9b6989ab396a.PNG)

**Comment by apexad** [comment]
I sometimes have a similar issue. To solve it, I plugged the lightify hub into a smart plug which I programmed to shut off at 1:00 AM every day and then turn back on at 1:05 AM. No problems since!

**Comment by dmckillican** [comment]
I also have the same issue and find restarting the lightify hub resolves the issue. I also find that the lights usually fail to work with the lightify app at the same time, leaving me to conclude its an issue with the hub, not the home bridge plugin.

**Comment by mylesgray** [comment]
I have resolved this with some changes to the core https://github.com/mylesgray/node-lightify library.

I created a fork and published on npm with an updated version of this plugin, it should be a simple swap out:

https://github.com/mylesgray/homebridge-platform-lightify

    npm uninstall -g homebridge-platform-lightify
    npm install -g homebridge-platform-lightify-mg

**Comment by crosenkr** [comment]
After the latest update yesterday, I get the error again.

First, the plugin loads fine. Then after some time: timeout.

[4/17/2019, 10:34:05 AM] [Lightify] Discover Failed
[4/17/2019, 10:34:05 AM] [Lightify] timeout
