### ISSUE TITLE
RGB Color setting

### ISSUE THREAD

**Issue by drjamiwe** [rainlake/homebridge-platform-lightify#17]
Hi! Sadly yours is the only partially working Lightify plugin for the Homebridge but sadly it won't change the color of my PAR16 RGBW.

This plugin will let you change the colors, but lacks a few features and is completely unstable.

https://github.com/chris1705/homebridge-lightify

Is there any chance of including the RGB compatibility for the PAR16 RGBW Lamps?
Thanks in advance!

**Comment by devenbj** [comment]
Found a few code changes that improved color changing for me. Both in: index.js

Change:
this.service.getCharacteristic(Characteristic.Saturation).value = hsv.h * 100;
    
To:
this.service.getCharacteristic(Characteristic.Saturation).value = hsv.s * 100;

Change:
c = device.blue;

To:
zone.blue = device.blue;

These changes require a restart to your homebridge.

**Comment by mman** [comment]
Just played with the plugin, these are obvious and correct changes. @rainlake Shall I create a pull request for you to merge?

**Comment by rainlake** [comment]
Awesome, thanks
