### ISSUE TITLE
Discovered failed connect timeout

### ISSUE THREAD

**Issue by SiGmAX666** [rainlake/homebridge-platform-lightify#23]
Edit: Config issue. I used the wrong freaking variable. RTFM. PEBKAC!

**Comment by dalethomas81** [comment]
Try pinging the Lightify gateway from the Docker container and also check your firewall settings. From the log, it looks like either 192.168.50.102 is not the Lightify gateways address or it cannot reach the gateway. Also, make sure your homebridge-lightify instance is not running simultaneously.

**Comment by SiGmAX666** [comment]
The other instance is definitely not running, I removed and replaced it for testing purposes. I am pretty familiar with Docker as I've used it for 3yrs and run 30+ containers currently, I am sure I did this part correctly.

That is also definitely the static IP of Lightify - I assign static up to x.200 on my IoT subnet - and it is pingable from within the container. Same IP also works great under homebridge-lightify.

**Comment by SiGmAX666** [comment]
Bump..any other input?

**Comment by dalethomas81** [comment]
This is a curious issue but I’m certain it’s not this plugin causing this. Did you try turning off your firewall? The gateway uses port 4000. Even though you can ping it you may need to open that port. I don’t know enough about Docker to speak on that. Also, I recommend moving over to node-red and using the node-Lightify library directly. This is what I have done and haven’t looked back.

**Comment by SiGmAX666** [comment]
With great embarrassment, I confess to PEBKAC. I re-RTFM tonight and started with a fresh fresh RPi running Homebridge in Docker and it is working great. The issue was my config. I started with a fresh config and noticed the error in my ways. `bridge_ip` vs `host` from other lightify plugins. Oops.

Also @dalethomas81 I do plan to Node-RED to the Dockerized RPi in the future, it's how I control some DIY IoT devices at a different location (also running on RPi with Docker). I highly suggest Docker for any sort of appliance application, it adds minimal overhead and makes upgrades and backups much easier through segmentation.
