### ISSUE TITLE
Color/Temperature change in Home App for Tunable Whites.

### ISSUE THREAD

**Issue by apexad** [rainlake/homebridge-platform-lightify#6]
Check out either of these:
https://github.com/chris1705/homebridge-lightify
https://github.com/lbohlmann/homebridge-lightify-tunablewhite-e14

Both use node-lightify but then apply the correct characteristics to make this possible.

If you don't get to it, I may try and bring it over and I would send you a pull request.

**Comment by rainlake** [comment]
That would be very nice. I personally do not own any tunable white bulbs.
Thanks!

**Comment by rainlake** [comment]
I did started working on it but can not test since I do not have any of those bulbs. I think it would be similar to HSVtoRGB and RGBtoHSV, but I do not know what to do with color selection because temperature only support very narrow part of full corlor

**Comment by apexad** [comment]
Are you able to push up a branch of what you have done so far so I can take a look and do some testing? I have not been able to work on this yet. Busy week for me!

**Comment by rainlake** [comment]
I pushed my changes to master but did not call the method.
I think I'm doing the wrong way. you CAN set temperature in Home app but it's pretty complicated. there could be some settings to figure out.

**Comment by apexad** [comment]
Thanks. I will take a look sometime this week. My parents were visiting last week, and I was very busy. Should have more time this week.
