### ISSUE TITLE
Feature Request: Lightify Groups Dimmable

### ISSUE THREAD

**Issue by dmckillican** [rainlake/homebridge-platform-lightify#8]
Hi Rainlake (me again...)

Groups are now working perfectly, and are very responsive (almost instant to voice commands). I note however that lightly groups are showing as a switch, not a dimmer, meaning I am unable to dim the lights. Is this possible?

No rush in the meantime - working! Thank you again.

**Comment by apexad** [comment]
I might try and look into this if rainlake does not get to it before me.

**Comment by dmckillican** [comment]
Great, thank you. Turns out that our biggest hardware store here in Australia (Bunnings) has discontinued lightify now so I managed to buy the stock of TW bulbs for $2 each! (usually $80). So I'm full committed to them now ;) I might even need a second hub.

**Comment by dmckillican** [comment]
Rainlakes group update is working perfectly - really awesome actually. The only drag now is that I have to use the Osram app to dim and tune.

**Comment by apexad** [comment]
That is crazy! Good for you.
You'll be excited once my Tunable white PR is looked at at by rainlake and merged.

**Comment by dmckillican** [comment]
I sure will be - 40 of my ceiling mounted GU10s are tuneable white - I only use the RGB lights in lamps

**Comment by rainlake** [comment]
fixed, ver 0.3.0

**Comment by dmckillican** [comment]
Great thank you so much!! I cannot test until next weekend as I'm down in Sydney for work for a few days. than you again. I'll let you know when that its working. All the best!

**Comment by apexad** [comment]
I was able to test on my dining room lights (dimmable) and my 2 bedroom lights (tunable white).  Worked great in both cases.

**Comment by dmckillican** [comment]
I have tested this now on my setup and it works just fine! I can't think of anything more to add now... it's perfect. Thank you very much guys.
